#!/usr/bin/env python
"""
Generic conversion from 'C API headers' to 'Mojo'.
(c) 2026 Jan Hercek; vibe coded with the Gemini 3 Flash.

TOOL LICENSE (this file):
Licensed under the GNU Affero General Public License v3.0.
Free to use, modify, and share. Any derivative work or
network-based use must remain Open Source under the AGPL.
See <https://www.gnu.org/licenses/agpl-3.0.html> for details.

OUTPUT LICENSE:
All code generated by this tool is licensed under the MIT License.
Permission is hereby granted to use, copy, and distribute output
of this file in any project, including commercial ones.
"""
# ruff: noqa:PTH110,PTH118,PTH120

VERSION = '1.0.0'
DATE = 'May 2026'

# Only 'C API' generation,
# Mojo doesn't support C++ class inheritance, so to correctly handle this
# we will need to create a small C wrapper first, and then use this program
# on the wrapper.

import sys
import argparse
import os
import re
from dataclasses import dataclass
import clang.cindex as cci  # type:ignore[import-untyped]

# We are ignoring #defines started with
BLACKLIST = {'_', 'va_list'}

# We are addind _ into these functions_arguments_names
MOJO_RESERVED = {
    'fn',
    'struct',
    'trait',
    'var',
    'let',
    'alias',
    'borrowed',
    'inout',
    'owned',
    'transfer',
    'self',
}

# Handle C-specific predefined macros
C_TO_MOJO_MACROS = {
    '__func__': '"<c_function>"',
    '__FUNCTION__': '"<c_function>"',
    '__FILE__': '"<c_file>"',
    '__FILE_NAME__': '"<c_file_name>"',
    '__LINE__': '0', # Mojo uses 'comptime' which may not track C line numbers
}

# --- 1. THE INTERMEDIATE REPRESENTATION (IR) ---
# This defines "What" we found, independent of how we print it.


@dataclass
class MojoDefine:
    name: str
    value: str


@dataclass
class MojoArg:
    name: str
    m_type: str


@dataclass
class MojoEnum:
    name: str
    constants: list[MojoDefine]
    base: str


@dataclass
class MojoStruct:
    name: str
    fields: list[MojoArg]
    is_opaque: bool


@dataclass
class MojoFunc:
    name: str
    args: list[MojoArg]
    ret_type: str


# --- 2. THE TYPE RESOLVER ENGINE ---


class TypeResolver:
    def __init__(self) -> None:
        # The "Allowed Tokens" lookup table
        self.type_map = {
            # Mojo's and CPU's architecture
            '__enum_base__': 'UInt32',
            '__unnamed_struct__': 'NoneType',
            '__default_blob__': 'UInt8',  # when everything else fails
            # Standard C pointers
            'void *': 'UnsafePointer[UInt8, StaticConstantOrigin]',
            'char *': 'UnsafePointer[UInt8, StaticConstantOrigin]',
            'c_char *': 'UnsafePointer[Int8, StaticConstantOrigin]',
            'c_uchar *': 'UnsafePointer[UInt8, StaticConstantOrigin]',
            # Mojo's ffi C types
            'c_char': 'Int8',
            'c_double': 'Float64',
            'c_float': 'Float32',
            'c_int': 'Int32',
            'c_long': 'Scalar[_c_long_dtype()]',
            'c_long_long': 'Scalar[_c_long_long_dtype()]',
            'c_pid_t': 'Int',
            'c_short': 'Int16',
            'c_size_t': 'UInt',
            'c_ssize_t': 'Int',
            'c_uchar': 'UInt8',
            'c_uint': 'UInt32',
            'c_ulong': 'Scalar[_c_long_dtype[True]()]',
            'c_ulong_long': 'Scalar[_c_long_long_dtype[True]()]',
            'c_ushort': 'UInt16',
            # Canonical C types
            'void': 'NoneType',
            'char': 'UInt8',
            'signed char': 'Int8',
            'unsigned char': 'UInt8',
            'int': 'Int32',
            'unsigned int': 'UInt32',
            'long': 'Int64',
            'unsigned long': 'UInt64',
            'long long': 'Int64',
            'unsigned long long': 'UInt64',
            'short': 'Int16',
            'unsigned short': 'UInt16',
            'float': 'Float32',
            'double': 'Float64',
            'bool': 'Bool',
            '_Bool': 'Bool',
            # Fixed-width integers (stdint.h)
            'int8_t': 'Int8',
            'uint8_t': 'UInt8',
            'int16_t': 'Int16',
            'uint16_t': 'UInt16',
            'int32_t': 'Int32',
            'uint32_t': 'UInt32',
            'int64_t': 'Int64',
            'uint64_t': 'UInt64',
            # Size and Pointer types
            'size_t': 'UIntPtr',
            'ssize_t': 'IntPtr',
            'intptr_t': 'IntPtr',
            'uintptr_t': 'UIntPtr',
            'ptrdiff_t': 'IntPtr',
            # C99/C11 specifics
            'float_t': 'Float32',
            'double_t': 'Float64',
            # Common OS/SDK aliases
            'uchar': 'UInt8',
            'uint': 'UInt32',
            'ulong': 'UInt64',
            'ushort': 'UInt16',
        }

    def strip_prefixes(self, name: str, prefixes: list[str]) -> str:
        for prefix in prefixes:
            name = name.replace(prefix, '')
        return name

    def resolve(self, clang_type: cci.Type, header_file: str = 'unknown') -> str:  # type:ignore[no-any-unimported] # noqa:C901
        # Check the map with the raw spelling first (e.g., 'size_t')
        # This preserves the "clean" name if we have it in our table.
        if clang_type.spelling in self.type_map:
            return self.type_map[clang_type.spelling]
        # If not found, get the canonical version
        canonical: cci.Type = clang_type.get_canonical()  # type:ignore[no-any-unimported]
        # Check the map again with the canonical spelling (e.g., 'unsigned long')
        if canonical.spelling in self.type_map:
            return self.type_map[canonical.spelling]
        # Strip prefixes
        stripped = self.strip_prefixes(canonical.spelling, ['const ', 'unsigned '])
        if stripped in self.type_map:
            return self.type_map[stripped]
        #
        # Handle Function Prototypes
        if '(' in canonical.spelling and ')' in canonical.spelling:
            # If it's a pointer to a function
            func_type = canonical
            if canonical.kind == cci.TypeKind.POINTER:
                func_type = canonical.get_pointee()
            try:
                ret_type = self.resolve(func_type.get_result_type())
                args = [self.resolve(arg) for arg in func_type.argument_types()]
                arg_str = ', '.join(args)
                # Returns Mojo's C-compatible function pointer type
                return f'def({arg_str}) thin abi("C") -> {ret_type}'  # noqa:TRY300
            except AttributeError:
                # Fallback for complex nested pointers
                return 'UnsafePointer[UInt8, MutAnyOrigin]'
        #
        # Handle Pointers recursively (char** -> UnsafePointer[UnsafePointer[UInt8]])
        if canonical.kind == cci.TypeKind.POINTER:
            pointee: str = self.resolve(canonical.get_pointee())
            return f'UnsafePointer[{pointee}, MutAnyOrigin]'
        #
        # Handle Arrays recursively
        if canonical.kind in [cci.TypeKind.CONSTANTARRAY, cci.TypeKind.INCOMPLETEARRAY]:
            element: str = self.resolve(canonical.get_array_element_type())
            return f'UnsafePointer[{element}, MutAnyOrigin]'
        #
        # Handle Enums
        if canonical.kind == cci.TypeKind.ENUM:
            e_name = self.strip_prefixes(canonical.spelling, ['const ', 'enum '])
            return e_name or self.type_map['__enum_base__']
        #
        # Handle Records (Structs + Unions)
        if canonical.kind == cci.TypeKind.RECORD:
            s_name = self.strip_prefixes(canonical.spelling, ['const ', 'struct ', 'union '])
            return s_name or self.type_map['__unnamed_struct__']
        #
        # Program should never fall here
        print('ERROR: Unrecognized type:', canonical.spelling)
        print(f'Input file: {header_file}.')
        print('Output .mojo file is unusable.')
        # breakpoint()
        sys.exit(2)


# --- 3. THE CODE EMITTER ---
# This is the "Backend" that turns IR objects into actual Mojo text.


class MojoEmitter:
    """Mojo version 1.0.0b1.dev*."""

    def __init__(self) -> None:
        self.first_define: bool = True  # first define in sequence

    @staticmethod
    def emit_header(header_files: list[tuple[str, bool]], so_file: str) -> str:
        out = '"""\n'
        out += '    C-API Wrapper\n'
        out += '    =============\n'
        out += f'    Generated Interface for {so_file} integration.\n'
        out += '\n'
        out += '    SOURCE FILES:\n'
        for hf, fi in header_files:
            out += f'       - {hf} [{"Defines & Structs Only" if not fi else "Full Bindings"}]\n'
        out += '\n'
        out += '    GENERATOR:\n'
        out += f'        Tool:    c-mojo-bridge.py (v {VERSION})\n'
        out += f'        Date:    {DATE}\n'
        out += '        Author:  Jan Hercek, vibe coded with the Gemini 3 Flash\n'
        out += '        License: GNU Affero General Public License v3.0.\n'
        out += '\n'
        out += '    THIS FILE LICENSE:\n'
        out += '        This file is licensed under the MIT License.\n'
        out += '        Permission is hereby granted to use, copy, and distribute\n'
        out += '        this file in any project, including commercial ones.\n'
        out += '\n'
        out += '    WARNING:\n'
        out += '        This file is AUTOGENERATED. Manual changes will be lost on regeneration.\n'
        out += '"""\n'
        out += 'from std import ffi\n'
        # out += "from std.ffi import external_call\n"
        return out

    def _sanitize_identifier(self, name: str) -> str:
        # Appends _ to reserved Mojo keywords.
        return f'{name}_' if name in MOJO_RESERVED else name

    def _sanitize_value(self, clang_value: str) -> str:
        # Sanitizes C numeric suffixes and predefined C macros.
        if clang_value in C_TO_MOJO_MACROS:
            return C_TO_MOJO_MACROS[clang_value]
        # Handle trailing u, l, f (e.g., 0x1u -> 0x1)
        return re.sub(r'(?<=\d)[uUlLfF]+$', '', clang_value)

    def emit_string(self, s: str) -> str:
        self.first_define = True
        return s

    def emit_define(self, a: MojoDefine) -> str:
        a.value = self._sanitize_value(a.value)
        out: str = f'{"\n" if self.first_define else ""}comptime {a.name} = {a.value}\n'
        self.first_define = False
        return out

    def emit_enum(self, e: MojoEnum) -> str:
        self.first_define = True
        # 1. The Type Wrapper
        out = f'\n# enum\ncomptime {e.name} = {e.base}\n'
        # 2. Global Constants, dedented for flat namespace
        for c in e.constants:
            out += f'comptime {c.name}: {e.name} = {c.value}\n'
        return out

    def emit_constructor(self, s: MojoStruct) -> str:
        # Called from emit_union() and from emit_struct()
        # Generate struct members
        out = ''
        if s.is_opaque:
            return out + '    pass\n'
        for f in s.fields:
            out += f'    var {f.name}: {f.m_type}\n'
        # Initialize members var's to a safe zero/null state
        out += '    def __init__(out self):\n'
        for f in s.fields:
            if 'UnsafePointer' in f.m_type:
                out += f'        self.{f.name} = {f.m_type}.unsafe_dangling()\n'
            else:
                out += f'        self.{f.name} = {f.m_type}()\n'
        return out

    def emit_union(self, s: MojoStruct) -> str:
        self.first_define = True
        traits = ''  # "(ImplicitlyCopyable, Movable)"
        out = f'\n# union\nstruct {s.name}{traits}:\n'
        out += self.emit_constructor(s)
        return out

    def emit_struct(self, s: MojoStruct) -> str:
        self.first_define = True
        traits = '(ImplicitlyCopyable, Movable)'
        out = f'\n# struct\n@fieldwise_init\nstruct {s.name}{traits}:\n'
        out += self.emit_constructor(s)
        return out

    #   def emit_func(self, f: MojoFunc) -> str:
    #       self.first_define = True
    #       args = ", ".join([f"{a.name}: {a.m_type}" for a in f.args])
    #       params = ", ".join([a.name for a in f.args])
    #       return (f"\ndef {f.name}({args}) -> {f.ret_type}:\n"
    #               f"    return external_call[\"{f.name}\", {f.ret_type}]({params})\n")

    def emit_func_declaration(self, f: MojoFunc) -> str:
        # Emits the 'var' declaration with the function type
        self.first_define = True
        arg_str = ', '.join([f'{self._sanitize_identifier(a.name)}: {a.m_type}' for a in f.args])
        return f'    var {f.name}:\n        def({arg_str}) thin abi("C") -> {f.ret_type}\n'

    def emit_func_assignment(self, f: MojoFunc) -> str:
        # Emits the lookup line for __init__
        self.first_define = True
        return (
            f'        self.{f.name} = self.lib.get_function[type_of(self.{f.name})]("{f.name}")\n'
        )

    def emit_functions(self, all_functions: list[MojoFunc], so_file: str) -> str:
        # Emit Pointers structure, which keeps all functions and lib handle
        self.first_define = True
        emitter = MojoEmitter()
        out: str = '\n# functions'
        out += '\nstruct Pointers:\n'
        out += '    var lib: ffi.OwnedDLHandle\n'
        # Declarations Pass
        for f in all_functions:
            out += emitter.emit_func_declaration(f)
        # Constructor Pass
        out += '    def __init__(out self) raises:\n'
        out += f'        self.lib = ffi.OwnedDLHandle("{so_file}")\n'
        for f in all_functions:
            out += emitter.emit_func_assignment(f)
        return out


# --- 4. THE OUTPUTER ---
class Outputer:
    def __init__(self, mojo_file: str = '') -> None:
        self.handle = open(mojo_file, 'w', encoding='utf-8') if mojo_file else None  # noqa:SIM115

    def run(self, msg: str) -> None:
        if self.handle:
            self.handle.write(msg)
        else:
            print(msg, end='')

    def close(self) -> None:
        if self.handle:
            self.handle.close()


# --- 5. THE ORCHESTRATOR ---
class Orchestrator:
    def __init__(
        self,
        types: list[str],
        functions: list[str],
        master: str,
        exclude: list[str],
        so_file: str,
        mojo_file: str = '',
        blacklist: list[str] | None = None,
    ) -> None:
        #
        self.header_files = []
        if master:
            self._expand_master(master)
        # The tuple (header_file_name, process_functions)
        self.header_files += [(h, False) for h in types] + [(f, True) for f in functions]
        if exclude:
            # We filter by checking if the filename is in the exclude list
            # We use os.path.basename to allow matching by just the filename
            self.header_files = [
                (path, is_func)
                for path, is_func in self.header_files
                if path not in exclude and os.path.basename(path) not in exclude  # noqa:PTH119
            ]
        # To be coded into output .mojo
        self.so_file = so_file
        # Empty mojo_file -> output will be printed to console
        self.mojo_file = mojo_file
        self.blacklist = BLACKLIST.union(set(blacklist or []))

    def _expand_master(self, master_path: str) -> None:
        """Parses a master header for #include "..." and adds them to the queue."""
        if not os.path.exists(master_path):
            print(f'ERROR: Master header {master_path} not found.')
            sys.exit(1)
        # We use a simple regex to find includes in the master file
        include_re = re.compile(r'#\s*include\s+["<]([^">]+)[">]')
        base_dir = os.path.dirname(master_path)
        with open(master_path) as f:
            for line in f:
                match = include_re.search(line)
                if match:
                    inc_file = match.group(1)
                    # Try to resolve relative to master file if it's a local include
                    full_path = os.path.join(base_dir, inc_file) if base_dir else inc_file
                    if os.path.exists(full_path):
                        self.header_files.append((full_path, True))
                    else:
                        # Fallback to the name itself (system headers or relative to include path)
                        self.header_files.append((inc_file, True))

    def run(self) -> None:  # noqa:C901
        """Core parser+generator logic."""
        index = cci.Index.create()
        resolver = TypeResolver()
        emitter = MojoEmitter()
        outputer = Outputer(self.mojo_file)
        # Functions saved for pass.2
        all_functions = []
        # Master memory, to prevent duplication of the:
        seen_macros = set()  # #defines
        seen_types = set()  # Structs and Enums
        seen_funcs = set()  # Functions
        #
        outputer.run(emitter.emit_header(self.header_files, self.so_file))
        for header_file, process_functions in self.header_files:
            # Detailed processing is needed to "see" #defines
            # without #defines, will be enough: tu = index.parse(header_file)
            try:
                tu: cci.TranslationUnit = index.parse(  # type:ignore[no-any-unimported]
                    header_file, options=cci.TranslationUnit.PARSE_DETAILED_PROCESSING_RECORD
                )
            except cci.TranslationUnitLoadError:
                print(f"ERROR: Unable to read+parse the '{header_file}'.")
                print('Can not continue. Output .mojo file is unusable.')
                sys.exit(1)
            #
            outputer.run(emitter.emit_string(f'\n# header file = {header_file}\n'))
            #
            for node in tu.cursor.get_children():
                # Location & blacklist filters
                if not node.location.file or node.location.file.name != header_file:
                    continue
                if any(node.spelling.startswith(p) for p in self.blacklist):
                    continue
                #
                # Handle #define
                if node.kind == cci.CursorKind.MACRO_DEFINITION:
                    tokens: list[cci.Token] = list(node.get_tokens())  # type:ignore[no-any-unimported]
                    # We look for simple pairs like #define NAME VALUE
                    if len(tokens) == 2:  # noqa:PLR2004
                        if node.spelling in seen_macros:
                            continue
                        alias_data = MojoDefine(tokens[0].spelling, tokens[1].spelling)
                        outputer.run(emitter.emit_define(alias_data))
                        seen_macros.add(node.spelling)
                    continue
                #
                # Handle enums
                if node.kind == cci.CursorKind.ENUM_DECL:
                    # Capture the name even from typedef enum { ... } Name;
                    raw_name = node.spelling or node.type.spelling
                    enum_name = raw_name.replace('enum ', '').strip()
                    # Skip truly unnamed internal enums
                    if not enum_name or enum_name == 'AnonymousEnum':
                        continue
                    constants: list[MojoDefine] = [
                        MojoDefine(c.spelling, str(c.enum_value))
                        for c in node.get_children()
                        if c.kind == cci.CursorKind.ENUM_CONSTANT_DECL
                    ]
                    if constants:
                        if enum_name in seen_types:
                            continue
                        enum_base = resolver.type_map['__enum_base__']
                        enum_data = MojoEnum(enum_name, constants, enum_base)
                        outputer.run(emitter.emit_enum(enum_data))
                        seen_types.add(enum_name)
                    continue
                #
                # Handle Structs and Unions
                if node.kind in [cci.CursorKind.STRUCT_DECL, cci.CursorKind.UNION_DECL]:
                    if node.spelling in seen_types:
                        continue
                    fields: list[MojoArg] = [
                        MojoArg(f.spelling, resolver.resolve(f.type, header_file))
                        for f in node.get_children()
                        if f.kind == cci.CursorKind.FIELD_DECL
                    ]
                    struct_data = MojoStruct(node.spelling, fields, is_opaque=len(fields) == 0)
                    if node.kind == cci.CursorKind.UNION_DECL:
                        outputer.run(emitter.emit_union(struct_data))
                    else:
                        outputer.run(emitter.emit_struct(struct_data))
                    seen_types.add(node.spelling)
                    continue
                #
                # Some headers need to be used only for theirs #defines, enums, and structs
                # So, Skip Functions generation, if required
                if not process_functions:
                    continue
                #
                # Handle Functions: pass.1 = collect
                if node.kind == cci.CursorKind.FUNCTION_DECL:
                    if node.spelling in seen_funcs:
                        continue
                    args: list[MojoArg] = [
                        MojoArg(p.spelling or f'arg{i}', resolver.resolve(p.type, header_file))
                        for i, p in enumerate(node.get_arguments())
                    ]
                    func_data = MojoFunc(
                        node.spelling, args, resolver.resolve(node.result_type, header_file)
                    )
                    # print(emitter.emit_func(func_data))  # Instead of pass.2 we can uncomment this
                    all_functions.append(func_data)  # and commentout this
                    seen_funcs.add(node.spelling)
                    continue
        # Handle Functions: pass.2 = output
        outputer.run(emitter.emit_functions(all_functions, self.so_file))
        outputer.run(emitter.emit_string('# eof\n'))
        outputer.close()


def main() -> None:
    msg: str = "c-mojo-bridge: Generic conversion from 'C API headers' to 'Mojo'."
    parser = argparse.ArgumentParser(description=msg)
    parser.add_argument('-o', '--output', help='Output Mojo file (default: print to console)')
    parser.add_argument(
        '-l', '--library', required=True, help='The .so/.dll library filename (e.g. libSDL3.so)'
    )
    parser.add_argument(
        '-t', '--types', nargs='*', default=[], help='Headers for types/enums/structs only'
    )
    parser.add_argument(
        '-f', '--functions', nargs='*', default=[], help='Headers for full functions bindings'
    )
    parser.add_argument('-m', '--master', help='Process all #includes in this master header')
    parser.add_argument(
        '-e',
        '--exclude',
        nargs='*',
        default=[],
        help='List of header files to exclude from processing',
    )
    parser.add_argument(
        '-b',
        '--blacklist',
        nargs='*',
        default=['G_', 'GLIB_'],
        help='Additional prefixes to ignore (default: G_, GLIB_)',
    )
    args = parser.parse_args()
    if not args.types and not args.functions and not args.master:
        parser.error('Provide at least one header via --types, --functions, or --master')
    orch = Orchestrator(
        types=args.types,
        functions=args.functions,
        master=args.master,
        exclude=args.exclude,
        so_file=args.library,
        mojo_file=args.output or '',
        blacklist=args.blacklist,
    )
    if args.output:
        print(f'Processing {len(orch.header_files)} files ...')
    orch.run()
    if args.output:
        print('Generation Complete.')


if __name__ == '__main__':
    main()

# eof
