#!/usr/bin/env python
"""
Generic conversion from 'C API headers' to 'Mojo'.
(c) 2026 Jan Hercek; vibe coded with the Gemini 3 Flash.

TOOL LICENSE (this file):
Licensed under the GNU Affero General Public License v3.0.
Free to use, modify, and share. Any derivative work or
network-based use must remain Open Source under the AGPL.
See <https://www.gnu.org/licenses/agpl-3.0.html> for details.

OUTPUT LICENSE:
All code generated by this tool is licensed under the MIT License.
Permission is hereby granted to use, copy, and distribute output
of this file in any project, including commercial ones.
"""
# ruff: noqa:PTH100,PTH110

# This program version:
VERSION = '1.1.0'

# Last updated for Mojo, version:
MOJO_VERSION = '1.0.0b1'

# Only 'C API' generation,
# Because Mojo doesn't support C++ class inheritance.
#
# how to overcome: create a small C wrapper first, and then use this program
# on the wrapper.

import os
import sys
import argparse
from dataclasses import dataclass
from typing import TypeAlias
import clang.cindex as cci  # type:ignore[import-untyped]

# We are ignoring #defines started with
BLACKLIST = {'_', 'va_list'}

# We are adding _ into these functions_arguments_names
MOJO_RESERVED = {
    'fn',
    'struct',
    'trait',
    'var',
    'let',
    'alias',
    'borrowed',
    'inout',
    'owned',
    'transfer',
    'self',
}

# C primitives conversion table
C_MOJO_TYPE_MAP = {
    # Mojo's and CPU's architecture
    '__enum_base__': 'UInt32',
    '__unnamed_struct__': 'NoneType',
    '__default_blob__': 'UInt8',  # when everything else fails
    # Standard C pointers
    'void *': 'UnsafePointer[UInt8, StaticConstantOrigin]',
    'char *': 'UnsafePointer[UInt8, StaticConstantOrigin]',
    'c_char *': 'UnsafePointer[Int8, StaticConstantOrigin]',
    'c_uchar *': 'UnsafePointer[UInt8, StaticConstantOrigin]',
    # Mojo's ffi C types
    'c_char': 'Int8',
    'c_double': 'Float64',
    'c_float': 'Float32',
    'c_int': 'Int32',
    'c_long': 'Scalar[_c_long_dtype()]',
    'c_long_long': 'Scalar[_c_long_long_dtype()]',
    'c_pid_t': 'Int',
    'c_short': 'Int16',
    'c_size_t': 'UInt',
    'c_ssize_t': 'Int',
    'c_uchar': 'UInt8',
    'c_uint': 'UInt32',
    'c_ulong': 'Scalar[_c_long_dtype[True]()]',
    'c_ulong_long': 'Scalar[_c_long_long_dtype[True]()]',
    'c_ushort': 'UInt16',
    # Canonical C types
    'void': 'NoneType',
    'char': 'UInt8',
    'signed char': 'Int8',
    'unsigned char': 'UInt8',
    'int': 'Int32',
    'unsigned int': 'UInt32',
    'long': 'Int64',
    'unsigned long': 'UInt64',
    'long long': 'Int64',
    'unsigned long long': 'UInt64',
    'short': 'Int16',
    'unsigned short': 'UInt16',
    'float': 'Float32',
    'double': 'Float64',
    'bool': 'Bool',
    '_Bool': 'Bool',
    # Fixed-width integers (stdint.h)
    'int8_t': 'Int8',
    'uint8_t': 'UInt8',
    'int16_t': 'Int16',
    'uint16_t': 'UInt16',
    'int32_t': 'Int32',
    'uint32_t': 'UInt32',
    'int64_t': 'Int64',
    'uint64_t': 'UInt64',
    # Size and Pointer types
    'size_t': 'AnyPointer',
    'ssize_t': 'AnyPointer',
    'intptr_t': 'AnyPointer',
    'uintptr_t': 'AnyPointer',
    'ptrdiff_t': 'AnyPointer',
    # C99/C11 specifics
    'float_t': 'Float32',
    'double_t': 'Float64',
    # Common OS/SDK aliases
    'uchar': 'UInt8',
    'uint': 'UInt32',
    'ulong': 'UInt64',
    'ushort': 'UInt16',
}

# Types + Traits + Origins
MOJO_TYPES = {
    'Int8',
    'UInt8',
    'Int16',
    'UInt16',
    'Int32',
    'UInt32',
    'Int64',
    'UInt64',
    'Float16',
    'Float32',
    'Float64',
    'Bool',
    'Int',
    'String',
    'StringRef',
    'Pointer',
    'UnsafePointer',
    'AnyPointer',
    'Reference',
    'None',
    'NoneType',
    'AnyType',
    'Copyable',
    'ImplicitlyCopyable',
    'ImplicitlyDestructible',
    'Movable',
    'RegisterPassable',
    'TrivialRegisterPassable',
    'MutAnyOrigin',
    'MutExternalOrigin',
    'MutOrigin',
    'Never',
    'OriginSet',
    'StaticConstantOrigin',
    'Optional',
    'unsafe_dangling',
}
MOJO_TYPES |= set(C_MOJO_TYPE_MAP.values())


# --- 1. THE INTERMEDIATE REPRESENTATION (IR) ---
# This defines "What" we found, independent of how we print it.
#
@dataclass
class MojoDefine:
    name: str
    value: str


@dataclass
class MojoArg:
    name: str
    m_type: str


@dataclass
class MojoEnum:
    name: str
    constants: list[MojoDefine]
    base: str


@dataclass
class MojoUnion:
    name: str
    fields: list[MojoArg]
    is_opaque: bool


@dataclass
class MojoStruct:
    name: str
    fields: list[MojoArg]
    is_opaque: bool


@dataclass
class MojoFunc:
    name: str
    args: list[MojoArg]
    ret_type: str


TMojo: TypeAlias = MojoDefine | MojoEnum | MojoUnion | MojoStruct | MojoFunc


# --- 2. THE TYPE RESOLVER ENGINE ---
class TypeResolver:
    """Convert C type to Mojo type."""
    def strip_prefixes(self, name: str, prefixes: list[str]) -> str:
        for prefix in prefixes:
            name = name.removeprefix(prefix)
        return name

    def resolve(self, clang_type: cci.Type, h_file: str = 'unknown') -> str:  # type:ignore[no-any-unimported] # noqa:C901
        """Produce Mojo type corresponing to the clang_type."""
        # Check the map with the raw spelling first (e.g., 'size_t')
        # This preserves the "clean" name if we have it in our table.
        if clang_type.spelling in C_MOJO_TYPE_MAP:
            return C_MOJO_TYPE_MAP[clang_type.spelling]
        # If not found, get the canonical version
        canonical: cci.Type = clang_type.get_canonical()  # type:ignore[no-any-unimported]
        # Check the map again with the canonical spelling (e.g., 'unsigned long')
        if canonical.spelling in C_MOJO_TYPE_MAP:
            return C_MOJO_TYPE_MAP[canonical.spelling]
        # Strip prefixes
        stripped = self.strip_prefixes(canonical.spelling, ['const ', 'unsigned '])
        if stripped in C_MOJO_TYPE_MAP:
            return C_MOJO_TYPE_MAP[stripped]
        #
        # Handle Function Prototypes
        if '(' in canonical.spelling and ')' in canonical.spelling:
            # If it's a pointer to a function
            func_type = canonical
            if canonical.kind == cci.TypeKind.POINTER:
                func_type = canonical.get_pointee()
            try:
                ret_type = self.resolve(func_type.get_result_type())
                args = [self.resolve(arg) for arg in func_type.argument_types()]
                arg_str = ', '.join(args)
                # Returns Mojo's C-compatible function pointer type
                return f'def({arg_str}) thin abi("C") -> {ret_type}'  # noqa:TRY300
            except AttributeError:
                # Fallback for complex nested pointers
                return 'UnsafePointer[UInt8, MutAnyOrigin]'
        #
        # Handle Pointers recursively
        if canonical.kind == cci.TypeKind.POINTER:
            pointee: str = self.resolve(canonical.get_pointee())
            return f'UnsafePointer[{pointee}, MutAnyOrigin]'
        #
        # Handle Arrays recursively
        if canonical.kind in [cci.TypeKind.CONSTANTARRAY, cci.TypeKind.INCOMPLETEARRAY]:
            element: str = self.resolve(canonical.get_array_element_type())
            return f'UnsafePointer[{element}, MutAnyOrigin]'
        #
        # Handle Enums
        if canonical.kind == cci.TypeKind.ENUM:
            e_name = self.strip_prefixes(canonical.spelling, ['const ', 'enum '])
            return e_name or C_MOJO_TYPE_MAP['__enum_base__']
        #
        # Handle Records (Structs + Unions)
        if canonical.kind == cci.TypeKind.RECORD:
            s_name = self.strip_prefixes(canonical.spelling, ['const ', 'struct ', 'union '])
            return s_name or C_MOJO_TYPE_MAP['__unnamed_struct__']
        #
        # Program should never fall here
        print('ERROR: Unrecognized type:', canonical.spelling)
        print(f'Input file: {h_file}.')
        print('Output .mojo file is unusable.')
        sys.exit(2)


# --- 3. THE CODE EMITTER ---
class MojoEmitter:
    """Convert IR (internal representation) classes to Mojo's language text."""
    @staticmethod
    def emit_header(so_file: str) -> str:
        out = '"""\n'
        out += '    C-API Wrapper\n'
        out += '    =============\n'
        out += f'    Generated Interface for {so_file} integration.\n'
        out += '\n'
        # out += '    SOURCE FILES:\n'
        # for hf, fi in header_files:
        #     out += f'       - {hf} [{"Defines & Structs Only" if not fi else "Full Bindings"}]\n'
        # out += '\n'
        out += '    GENERATOR:\n'
        out += f'       Tool     : c_mojo_bridge.py (v {VERSION})\n'
        out += f'       Made for : Mojo v {MOJO_VERSION}\n'
        out += '       Author   : Jan Hercek, vibe coded with the Gemini 3 Flash\n'
        out += '       License  : GNU Affero General Public License v3.0.\n'
        out += '\n'
        out += '    THIS FILE LICENSE:\n'
        out += '        This file is licensed under the MIT License.\n'
        out += '        Permission is hereby granted to use, copy, and distribute\n'
        out += '        this file in any project, including commercial ones.\n'
        out += '\n'
        out += '    WARNING:\n'
        out += '        This file is AUTOGENERATED. Manual changes will be lost on regeneration.\n'
        out += '"""\n'
        out += 'from std import ffi\n'
        # out += "from std.ffi import external_call\n"
        return out

    def _sanitize_identifier(self, name: str) -> str:
        # Appends _ to reserved Mojo keywords.
        return f'{name}_' if name in MOJO_RESERVED else name

    def _sanitize_value(self, clang_value: str) -> str:
        # Handle hex trailing u,l (e.g., 0x1u -> 0x1)
        if clang_value and clang_value[0].isdigit():
            while clang_value[-1] in ('u', 'U', 'l', 'L'):
                clang_value = clang_value[:-1]
        return clang_value

    def emit_string(self, s: str) -> str:
        return s

    def emit_define(self, d: MojoDefine) -> str:
        d.value = self._sanitize_value(d.value)
        out: str = f'comptime {d.name} = {d.value}\n'
        return out

    def emit_enum(self, e: MojoEnum) -> str:
        # 1. The Type Wrapper
        out = f'\n# enum\ncomptime {e.name} = {e.base}\n'
        # 2. Global Constants, dedented for flat namespace
        for c in e.constants:
            out += f'comptime {c.name}: {e.name} = {self._sanitize_value(c.value)}\n'
        return out

    def _emit_constructor(self, s: MojoUnion | MojoStruct) -> str:
        """Generate struct members (=variables) for emit_union() or emit_struct()."""
        out = ''
        if s.is_opaque:
            return out + '    pass\n'
        for f in s.fields:
            out += f'    var {f.name}: {f.m_type}\n'
        # Initialize members var's to a safe zero/null state
        out += '    def __init__(out self):\n'
        for f in s.fields:
            if 'UnsafePointer' in f.m_type:
                out += f'        self.{f.name} = {f.m_type}.unsafe_dangling()\n'
            else:
                out += f'        self.{f.name} = {f.m_type}()\n'
        return out

    def emit_union(self, s: MojoUnion) -> str:
        traits = ''  # "(ImplicitlyCopyable, Movable)"
        out = f'\n# union\nstruct {s.name}{traits}:\n'
        out += self._emit_constructor(s)
        return out

    def emit_struct(self, s: MojoStruct) -> str:
        traits = '(ImplicitlyCopyable, Movable)'
        out = f'\n# struct\n@fieldwise_init\nstruct {s.name}{traits}:\n'
        out += self._emit_constructor(s)
        return out

    #   def emit_func(self, f: MojoFunc) -> str:
    #       args = ", ".join([f"{a.name}: {a.m_type}" for a in f.args])
    #       params = ", ".join([a.name for a in f.args])
    #       return (f"\ndef {f.name}({args}) -> {f.ret_type}:\n"
    #               f"    return external_call[\"{f.name}\", {f.ret_type}]({params})\n")

    def emit_func_declaration(self, f: MojoFunc) -> str:
        """Emits the 'var' declaration with the function type."""
        arg_str = ', '.join([f'{self._sanitize_identifier(a.name)}: {a.m_type}' for a in f.args])
        return f'    var {f.name}:\n        def({arg_str}) thin abi("C") -> {f.ret_type}\n'

    def emit_func_assignment(self, f: MojoFunc) -> str:
        """Emits the assignment line for Pointers.__init__."""
        return (
            f'        self.{f.name} = self.lib.get_function[type_of(self.{f.name})]("{f.name}")\n'
        )

    def emit_functions(self, all_functions: list[MojoFunc], so_file: str) -> str:
        """Emit Pointers structure, which keeps all functions and lib handle."""
        emitter = MojoEmitter()
        out: str = '\n# functions'
        out += '\nstruct Pointers:\n'
        out += '    var lib: ffi.OwnedDLHandle\n'
        # Declarations Pass
        for f in all_functions:
            out += emitter.emit_func_declaration(f)
        # Constructor Pass
        out += '    def __init__(out self) raises:\n'
        out += f'        self.lib = ffi.OwnedDLHandle("{so_file}")\n'
        for f in all_functions:
            out += emitter.emit_func_assignment(f)
        return out


# --- 4. THE OUTPUTER ---
class Outputer:
    """Output content to mojo_file, or print it to the stdout."""
    def __init__(self, mojo_file: str = '') -> None:
        self.handle = open(mojo_file, 'w', encoding='utf-8') if mojo_file else None  # noqa:SIM115

    def write(self, msg: str) -> None:
        if self.handle:
            self.handle.write(msg)
        else:
            print(msg, end='')

    def close(self) -> None:
        if self.handle:
            self.handle.close()


# --- 5. THE ORCHESTRATOR ---
class Orchestrator:
    def __init__(self, args: argparse.Namespace) -> None:
        """Prepare instance variables according to cli arguments."""
        self.header_files: list[tuple[str, bool]] = []
        if args.master:
            self._expand_master(args.master)
        # The tuple (header_file_name, process_functions)
        self.header_files += [(h, False) for h in args.types] + [(f, True) for f in args.functions]
        if args.exclude:
            # We filter by checking if the filename is in the exclude list
            # We use os.path.basename to allow matching by just the filename
            self.header_files = [
                (path, is_func)
                for path, is_func in self.header_files
                if path not in args.exclude and os.path.basename(path) not in args.exclude  # noqa:PTH119
            ]
        # To be coded into output .mojo
        self.so_file: str = args.library
        # Empty mojo_file -> output will be printed to console
        self.mojo_file: str = args.output
        self.blacklist: set[str] = BLACKLIST.union(set(args.blacklist or set()))
        self.required: set[str] = set(args.required)
        # Internal Storage: saved data for run:pass#2
        self.all_ids: dict[str, TMojo] = {}
        self.sorted_output: list[TMojo] = []

    def _expand_master(self, master_path: str) -> None:
        """Parses a master header using Clang to find all valid inclusion directives."""
        if not os.path.exists(master_path):
            print(f'ERROR: Master header {master_path} not found.')
            sys.exit(1)
        index = cci.Index.create()
        try:
            tu = index.parse(
                master_path, options=cci.TranslationUnit.PARSE_DETAILED_PROCESSING_RECORD
            )
        except cci.TranslationUnitLoadError:
            print(f"ERROR: Unable to parse master header '{master_path}'.")
            sys.exit(1)
        for node in tu.cursor.get_children():
            # INCLUSION_DIRECTIVE represents #include, #import, or #include_next

            if (
                node.location.file
                and os.path.abspath(node.location.file.name) == os.path.abspath(master_path)
                and node.kind == cci.CursorKind.INCLUSION_DIRECTIVE
            ):
                self.header_files.append((node.spelling, True))

    def _flat(self, names: list[str]) -> list[str]:
        """Each name can be structure, split it, dump mojo's known, return rest."""
        out: list[str] = []
        for name in names:
            words = name
            for delimiter in '[](),.':  # delimiters
                words = words.replace(delimiter, ' ')
            for id_ in words.split():
                if id_ not in MOJO_TYPES:
                    out.append(id_)  # noqa:PERF401
        return out

    def _get_deps_for_item(self, item: TMojo) -> list[str]:
        """Uniformly extracts potential internal dependencies from any IR object."""
        if isinstance(item, MojoUnion | MojoStruct):
            return self._flat([f.m_type for f in item.fields])
        if isinstance(item, MojoFunc):
            return self._flat([item.ret_type]) + self._flat([a.m_type for a in item.args])
        # if isinstance(item, MojoDefine | MojoEnum):
        return []

    def collect(self) -> None:  # noqa:C901
        """Core parser logic."""
        index = cci.Index.create()
        resolver = TypeResolver()
        for h_file, process_functions in self.header_files:
            # Detailed processing is needed to "see" #defines
            # without #defines, will be enough: tu = index.parse(h_file)
            try:
                tu: cci.TranslationUnit = index.parse(  # type:ignore[no-any-unimported]
                    h_file, options=cci.TranslationUnit.PARSE_DETAILED_PROCESSING_RECORD
                )
            except cci.TranslationUnitLoadError:
                print(f"ERROR: Unable to read+parse the '{h_file}'.")
                print('Can not continue. Output .mojo file is unusable.')
                sys.exit(1)
            for node in tu.cursor.get_children():
                # Location & blacklist filters
                if not node.location.file or node.location.file.name != h_file:
                    continue
                if any(node.spelling.startswith(p) for p in self.blacklist):
                    continue
                #
                if node.kind == cci.CursorKind.MACRO_DEFINITION:
                    # Only simple defines are processed
                    tokens = list(node.get_tokens())
                    if len(tokens) != 2:  # noqa:PLR2004
                        continue
                    number = tokens[1].spelling
                    if not number[0].isdigit():
                        continue
                    self.all_ids[node.spelling] = MojoDefine(node.spelling, number)
                    continue
                #
                if node.kind == cci.CursorKind.ENUM_DECL:
                    # Capture the name even from typedef enum { ... } Name;
                    raw_name = node.spelling or node.type.spelling
                    enum_name = raw_name.replace('enum ', '').strip()
                    # Skip truly unnamed internal enums
                    if not enum_name or 'unnamed' in enum_name:
                        continue
                    constants: list[MojoDefine] = [
                        MojoDefine(c.spelling, str(c.enum_value))
                        for c in node.get_children()
                        if c.kind == cci.CursorKind.ENUM_CONSTANT_DECL
                    ]
                    if constants:
                        enum_base = C_MOJO_TYPE_MAP['__enum_base__']
                        self.all_ids[enum_name] = MojoEnum(enum_name, constants, enum_base)
                    continue
                #
                if node.kind == cci.CursorKind.UNION_DECL:
                    values: list[MojoArg] = [
                        MojoArg(f.spelling, resolver.resolve(f.type, h_file))
                        for f in node.get_children()
                        if f.kind == cci.CursorKind.FIELD_DECL
                    ]
                    mu = MojoUnion(node.spelling, values, is_opaque=len(values) == 0)
                    self.all_ids[node.spelling] = mu
                    continue
                #
                if node.kind == cci.CursorKind.STRUCT_DECL:
                    fields: list[MojoArg] = [
                        MojoArg(f.spelling, resolver.resolve(f.type, h_file))
                        for f in node.get_children()
                        if f.kind == cci.CursorKind.FIELD_DECL
                    ]
                    ms = MojoStruct(node.spelling, fields, is_opaque=len(fields) == 0)
                    self.all_ids[node.spelling] = ms
                    continue
                #
                # Some headers need to be used only for theirs #defines, enums, and structs
                # So, Skip Functions generation, if required
                if not process_functions:
                    continue
                #
                # Handle Functions
                if node.kind == cci.CursorKind.FUNCTION_DECL:
                    args: list[MojoArg] = [
                        MojoArg(p.spelling or f'arg{i}', resolver.resolve(p.type, h_file))
                        for i, p in enumerate(node.get_arguments())
                    ]
                    mf = MojoFunc(node.spelling, args, resolver.resolve(node.result_type, h_file))
                    self.all_ids[node.spelling] = mf
                    continue

    def prune(self) -> None:
        """Only required identifiers and theirs ancestors should remain in our all_ids."""
        if not self.required:
            return
        keep = set()
        queue = self.required.copy()
        while queue:
            name = queue.pop()
            if name in keep or name in MOJO_TYPES:
                continue
            item = self.all_ids[name]
            if item:
                keep.add(name)
                for dep in self._get_deps_for_item(item):
                    if dep not in keep:
                        queue.add(dep)
        # Filter dictionary
        self.all_ids = {k: v for k, v in self.all_ids.items() if k in keep}

    def sort(self) -> None:
        """Reorder names from self.all_ids to ensure known first (for mojo compiler)."""
        visited = set()
        self.sorted_output = []

        def visit(name: str) -> None:
            if name in visited or name not in self.all_ids:
                return
            obj = self.all_ids[name]
            # Recursively visit dependencies first
            for dep in self._get_deps_for_item(obj):
                if dep != name:
                    visit(dep)
            # Only then add the name
            visited.add(name)
            self.sorted_output.append(obj)

        # Prioritize MojoDefine objects to push them to the top
        for name, obj in self.all_ids.items():
            if isinstance(obj, MojoDefine):
                visit(name)     
        # Reorder all_ids (defines are processed and will be skipped)
        for name in self.all_ids:
            visit(name)
        # Return is self.sorted_output

    def flush(self) -> None:
        """Save data to -o file _or_ print them to console."""
        emitter = MojoEmitter()
        outputer = Outputer(self.mojo_file)
        outputer.write(emitter.emit_header(self.so_file))
        first_define: bool = True
        all_functions: list[MojoFunc] = []
        for obj in self.sorted_output:
            if isinstance(obj, MojoDefine):
                if first_define:
                    first_define = False
                    outputer.write(emitter.emit_string('\n# defines\n'))
                outputer.write(emitter.emit_define(obj))
            elif isinstance(obj, MojoEnum):
                first_define = True
                outputer.write(emitter.emit_enum(obj))
            elif isinstance(obj, MojoUnion):
                first_define = True
                outputer.write(emitter.emit_union(obj))
            elif isinstance(obj, MojoStruct):
                first_define = True
                outputer.write(emitter.emit_struct(obj))
            elif isinstance(obj, MojoFunc):
                all_functions.append(obj)
        outputer.write(emitter.emit_functions(all_functions, self.so_file))
        outputer.write(emitter.emit_string('# eof\n'))
        outputer.close()


def get_arguments() -> argparse.Namespace:
    """Define & Parse CLI arguments."""
    msg: str = "c_mojo_bridge: Generic conversion from 'C API headers' to 'Mojo'."
    parser = argparse.ArgumentParser(description=msg)
    parser.add_argument('-o', '--output', help='Output Mojo file (default: print to console)')
    parser.add_argument(
        '-l', '--library', required=True, help='The .so/.dll library filename (e.g. libSDL3.so)'
    )
    parser.add_argument(
        '-t', '--types', nargs='*', default=[], help='Headers for types/enums/structs only'
    )
    parser.add_argument(
        '-f', '--functions', nargs='*', default=[], help='Headers for full functions bindings'
    )
    parser.add_argument('-m', '--master', help='Process all #includes in this master header')
    parser.add_argument(
        '-e',
        '--exclude',
        nargs='*',
        default=[],
        help='List of header files to exclude from processing',
    )
    parser.add_argument(
        '-b',
        '--blacklist',
        nargs='*',
        default=[],
        help='Additional identifier prefixes to ignore)',
    )
    parser.add_argument(
        '-r',
        '--required',
        nargs='*',
        default=[],
        help='Only emit these identifiers and their dependencies, default emit everything',
    )
    args = parser.parse_args()
    if not args.types and not args.functions and not args.master:
        parser.error('Provide at least one header via --types, --functions, or --master')
    return args


def main() -> None:
    """Create and run orchestrator."""
    args = get_arguments()
    orch = Orchestrator(args)
    if args.output:
        print(f'Processing {len(orch.header_files)} files ...')
    orch.collect()
    orch.prune()
    orch.sort()
    orch.flush()
    if args.output:
        print(f'Generation ({args.output}) complete.')


if __name__ == '__main__':
    main()

# eof
